version: '3'
services:
  mongodb:
    image: mongo:3.4.3
    networks:
      - webnet
    deploy:
      placement:
        constraints: [node.role == manager]
    logging:
      driver: "json-file"
  web:
    image: ceruberu/rian-note:latest
    deploy:
      replicas: 1
    # build: .
    # sequential_deployment: true
    ports:
      - "4000:4000"
      - "5000:5000"
      - "8080:8080"
    volumes:
      - data:/data/db
    depends_on:
      - mongodb
    # links:
      # - mongodb
    logging:
      driver: "json-file"
    networks:
      - webnet
    # env_file: ./config/node.env
networks:
  webnet:
volumes:
  data:
