version: "3"
services:
  web:
    image: ceruberu/rian-container:0.1.1
    build: .
    ports:
      - "4000:4000"
      - "5000:5000"
      - "8080:8080"
    volumes:
      - data:/data/db
    depends_on:
      - mongodb
    networks:
      - webnet
  mongodb:
    image: "mongo:3.4.3"
    networks:
      - webnet
volumes:
  data:
networks:
  webnet: