version: '3'
services:
  mongodb:
    image: ${MONGO}
    networks:
      - webnet
  web:
    image: ceruberu/rian-container:${IMAGE_VERSION}
    build: .
    ports:
      - "4000:4000"
      - "5000:5000"
      - "8080:8080"
    volumes:
      - data:${DATA_DIRECTORY}
    depends_on:
      - mongodb
    links:
      - mongodb
    networks:
      - webnet
    env_file: ./config/node.env
networks:
  webnet:
volumes:
  data:
