// flow-typed signature: ee82467ed2ac565304381b5134c815c2
// flow-typed version: <<STUB>>/froala-editor_v^2.6.0/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'froala-editor'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'froala-editor' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'froala-editor/html/3rd-party/require_js/js/app' {
  declare module.exports: any;
}

declare module 'froala-editor/html/3rd-party/require_js/js/lib/require' {
  declare module.exports: any;
}

declare module 'froala-editor/js/froala_editor.min' {
  declare module.exports: any;
}

declare module 'froala-editor/js/froala_editor.pkgd.min' {
  declare module.exports: any;
}

declare module 'froala-editor/js/languages/ar' {
  declare module.exports: any;
}

declare module 'froala-editor/js/languages/bs' {
  declare module.exports: any;
}

declare module 'froala-editor/js/languages/cs' {
  declare module.exports: any;
}

declare module 'froala-editor/js/languages/da' {
  declare module.exports: any;
}

declare module 'froala-editor/js/languages/de' {
  declare module.exports: any;
}

declare module 'froala-editor/js/languages/en_ca' {
  declare module.exports: any;
}

declare module 'froala-editor/js/languages/en_gb' {
  declare module.exports: any;
}

declare module 'froala-editor/js/languages/es' {
  declare module.exports: any;
}

declare module 'froala-editor/js/languages/et' {
  declare module.exports: any;
}

declare module 'froala-editor/js/languages/fa' {
  declare module.exports: any;
}

declare module 'froala-editor/js/languages/fi' {
  declare module.exports: any;
}

declare module 'froala-editor/js/languages/fr' {
  declare module.exports: any;
}

declare module 'froala-editor/js/languages/he' {
  declare module.exports: any;
}

declare module 'froala-editor/js/languages/hr' {
  declare module.exports: any;
}

declare module 'froala-editor/js/languages/hu' {
  declare module.exports: any;
}

declare module 'froala-editor/js/languages/id' {
  declare module.exports: any;
}

declare module 'froala-editor/js/languages/it' {
  declare module.exports: any;
}

declare module 'froala-editor/js/languages/ja' {
  declare module.exports: any;
}

declare module 'froala-editor/js/languages/ko' {
  declare module.exports: any;
}

declare module 'froala-editor/js/languages/me' {
  declare module.exports: any;
}

declare module 'froala-editor/js/languages/nb' {
  declare module.exports: any;
}

declare module 'froala-editor/js/languages/nl' {
  declare module.exports: any;
}

declare module 'froala-editor/js/languages/pl' {
  declare module.exports: any;
}

declare module 'froala-editor/js/languages/pt_br' {
  declare module.exports: any;
}

declare module 'froala-editor/js/languages/pt_pt' {
  declare module.exports: any;
}

declare module 'froala-editor/js/languages/ro' {
  declare module.exports: any;
}

declare module 'froala-editor/js/languages/ru' {
  declare module.exports: any;
}

declare module 'froala-editor/js/languages/sk' {
  declare module.exports: any;
}

declare module 'froala-editor/js/languages/sr' {
  declare module.exports: any;
}

declare module 'froala-editor/js/languages/sv' {
  declare module.exports: any;
}

declare module 'froala-editor/js/languages/th' {
  declare module.exports: any;
}

declare module 'froala-editor/js/languages/tr' {
  declare module.exports: any;
}

declare module 'froala-editor/js/languages/uk' {
  declare module.exports: any;
}

declare module 'froala-editor/js/languages/vi' {
  declare module.exports: any;
}

declare module 'froala-editor/js/languages/zh_cn' {
  declare module.exports: any;
}

declare module 'froala-editor/js/languages/zh_tw' {
  declare module.exports: any;
}

declare module 'froala-editor/js/plugins/align.min' {
  declare module.exports: any;
}

declare module 'froala-editor/js/plugins/char_counter.min' {
  declare module.exports: any;
}

declare module 'froala-editor/js/plugins/code_beautifier.min' {
  declare module.exports: any;
}

declare module 'froala-editor/js/plugins/code_view.min' {
  declare module.exports: any;
}

declare module 'froala-editor/js/plugins/colors.min' {
  declare module.exports: any;
}

declare module 'froala-editor/js/plugins/draggable.min' {
  declare module.exports: any;
}

declare module 'froala-editor/js/plugins/emoticons.min' {
  declare module.exports: any;
}

declare module 'froala-editor/js/plugins/entities.min' {
  declare module.exports: any;
}

declare module 'froala-editor/js/plugins/file.min' {
  declare module.exports: any;
}

declare module 'froala-editor/js/plugins/font_family.min' {
  declare module.exports: any;
}

declare module 'froala-editor/js/plugins/font_size.min' {
  declare module.exports: any;
}

declare module 'froala-editor/js/plugins/forms.min' {
  declare module.exports: any;
}

declare module 'froala-editor/js/plugins/fullscreen.min' {
  declare module.exports: any;
}

declare module 'froala-editor/js/plugins/help.min' {
  declare module.exports: any;
}

declare module 'froala-editor/js/plugins/image_manager.min' {
  declare module.exports: any;
}

declare module 'froala-editor/js/plugins/image.min' {
  declare module.exports: any;
}

declare module 'froala-editor/js/plugins/inline_style.min' {
  declare module.exports: any;
}

declare module 'froala-editor/js/plugins/line_breaker.min' {
  declare module.exports: any;
}

declare module 'froala-editor/js/plugins/link.min' {
  declare module.exports: any;
}

declare module 'froala-editor/js/plugins/lists.min' {
  declare module.exports: any;
}

declare module 'froala-editor/js/plugins/paragraph_format.min' {
  declare module.exports: any;
}

declare module 'froala-editor/js/plugins/paragraph_style.min' {
  declare module.exports: any;
}

declare module 'froala-editor/js/plugins/print.min' {
  declare module.exports: any;
}

declare module 'froala-editor/js/plugins/quick_insert.min' {
  declare module.exports: any;
}

declare module 'froala-editor/js/plugins/quote.min' {
  declare module.exports: any;
}

declare module 'froala-editor/js/plugins/save.min' {
  declare module.exports: any;
}

declare module 'froala-editor/js/plugins/special_characters.min' {
  declare module.exports: any;
}

declare module 'froala-editor/js/plugins/table.min' {
  declare module.exports: any;
}

declare module 'froala-editor/js/plugins/url.min' {
  declare module.exports: any;
}

declare module 'froala-editor/js/plugins/video.min' {
  declare module.exports: any;
}

declare module 'froala-editor/js/plugins/word_paste.min' {
  declare module.exports: any;
}

declare module 'froala-editor/js/third_party/image_aviary.min' {
  declare module.exports: any;
}

declare module 'froala-editor/js/third_party/spell_checker.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'froala-editor/html/3rd-party/require_js/js/app.js' {
  declare module.exports: $Exports<'froala-editor/html/3rd-party/require_js/js/app'>;
}
declare module 'froala-editor/html/3rd-party/require_js/js/lib/require.js' {
  declare module.exports: $Exports<'froala-editor/html/3rd-party/require_js/js/lib/require'>;
}
declare module 'froala-editor/js/froala_editor.min.js' {
  declare module.exports: $Exports<'froala-editor/js/froala_editor.min'>;
}
declare module 'froala-editor/js/froala_editor.pkgd.min.js' {
  declare module.exports: $Exports<'froala-editor/js/froala_editor.pkgd.min'>;
}
declare module 'froala-editor/js/languages/ar.js' {
  declare module.exports: $Exports<'froala-editor/js/languages/ar'>;
}
declare module 'froala-editor/js/languages/bs.js' {
  declare module.exports: $Exports<'froala-editor/js/languages/bs'>;
}
declare module 'froala-editor/js/languages/cs.js' {
  declare module.exports: $Exports<'froala-editor/js/languages/cs'>;
}
declare module 'froala-editor/js/languages/da.js' {
  declare module.exports: $Exports<'froala-editor/js/languages/da'>;
}
declare module 'froala-editor/js/languages/de.js' {
  declare module.exports: $Exports<'froala-editor/js/languages/de'>;
}
declare module 'froala-editor/js/languages/en_ca.js' {
  declare module.exports: $Exports<'froala-editor/js/languages/en_ca'>;
}
declare module 'froala-editor/js/languages/en_gb.js' {
  declare module.exports: $Exports<'froala-editor/js/languages/en_gb'>;
}
declare module 'froala-editor/js/languages/es.js' {
  declare module.exports: $Exports<'froala-editor/js/languages/es'>;
}
declare module 'froala-editor/js/languages/et.js' {
  declare module.exports: $Exports<'froala-editor/js/languages/et'>;
}
declare module 'froala-editor/js/languages/fa.js' {
  declare module.exports: $Exports<'froala-editor/js/languages/fa'>;
}
declare module 'froala-editor/js/languages/fi.js' {
  declare module.exports: $Exports<'froala-editor/js/languages/fi'>;
}
declare module 'froala-editor/js/languages/fr.js' {
  declare module.exports: $Exports<'froala-editor/js/languages/fr'>;
}
declare module 'froala-editor/js/languages/he.js' {
  declare module.exports: $Exports<'froala-editor/js/languages/he'>;
}
declare module 'froala-editor/js/languages/hr.js' {
  declare module.exports: $Exports<'froala-editor/js/languages/hr'>;
}
declare module 'froala-editor/js/languages/hu.js' {
  declare module.exports: $Exports<'froala-editor/js/languages/hu'>;
}
declare module 'froala-editor/js/languages/id.js' {
  declare module.exports: $Exports<'froala-editor/js/languages/id'>;
}
declare module 'froala-editor/js/languages/it.js' {
  declare module.exports: $Exports<'froala-editor/js/languages/it'>;
}
declare module 'froala-editor/js/languages/ja.js' {
  declare module.exports: $Exports<'froala-editor/js/languages/ja'>;
}
declare module 'froala-editor/js/languages/ko.js' {
  declare module.exports: $Exports<'froala-editor/js/languages/ko'>;
}
declare module 'froala-editor/js/languages/me.js' {
  declare module.exports: $Exports<'froala-editor/js/languages/me'>;
}
declare module 'froala-editor/js/languages/nb.js' {
  declare module.exports: $Exports<'froala-editor/js/languages/nb'>;
}
declare module 'froala-editor/js/languages/nl.js' {
  declare module.exports: $Exports<'froala-editor/js/languages/nl'>;
}
declare module 'froala-editor/js/languages/pl.js' {
  declare module.exports: $Exports<'froala-editor/js/languages/pl'>;
}
declare module 'froala-editor/js/languages/pt_br.js' {
  declare module.exports: $Exports<'froala-editor/js/languages/pt_br'>;
}
declare module 'froala-editor/js/languages/pt_pt.js' {
  declare module.exports: $Exports<'froala-editor/js/languages/pt_pt'>;
}
declare module 'froala-editor/js/languages/ro.js' {
  declare module.exports: $Exports<'froala-editor/js/languages/ro'>;
}
declare module 'froala-editor/js/languages/ru.js' {
  declare module.exports: $Exports<'froala-editor/js/languages/ru'>;
}
declare module 'froala-editor/js/languages/sk.js' {
  declare module.exports: $Exports<'froala-editor/js/languages/sk'>;
}
declare module 'froala-editor/js/languages/sr.js' {
  declare module.exports: $Exports<'froala-editor/js/languages/sr'>;
}
declare module 'froala-editor/js/languages/sv.js' {
  declare module.exports: $Exports<'froala-editor/js/languages/sv'>;
}
declare module 'froala-editor/js/languages/th.js' {
  declare module.exports: $Exports<'froala-editor/js/languages/th'>;
}
declare module 'froala-editor/js/languages/tr.js' {
  declare module.exports: $Exports<'froala-editor/js/languages/tr'>;
}
declare module 'froala-editor/js/languages/uk.js' {
  declare module.exports: $Exports<'froala-editor/js/languages/uk'>;
}
declare module 'froala-editor/js/languages/vi.js' {
  declare module.exports: $Exports<'froala-editor/js/languages/vi'>;
}
declare module 'froala-editor/js/languages/zh_cn.js' {
  declare module.exports: $Exports<'froala-editor/js/languages/zh_cn'>;
}
declare module 'froala-editor/js/languages/zh_tw.js' {
  declare module.exports: $Exports<'froala-editor/js/languages/zh_tw'>;
}
declare module 'froala-editor/js/plugins/align.min.js' {
  declare module.exports: $Exports<'froala-editor/js/plugins/align.min'>;
}
declare module 'froala-editor/js/plugins/char_counter.min.js' {
  declare module.exports: $Exports<'froala-editor/js/plugins/char_counter.min'>;
}
declare module 'froala-editor/js/plugins/code_beautifier.min.js' {
  declare module.exports: $Exports<'froala-editor/js/plugins/code_beautifier.min'>;
}
declare module 'froala-editor/js/plugins/code_view.min.js' {
  declare module.exports: $Exports<'froala-editor/js/plugins/code_view.min'>;
}
declare module 'froala-editor/js/plugins/colors.min.js' {
  declare module.exports: $Exports<'froala-editor/js/plugins/colors.min'>;
}
declare module 'froala-editor/js/plugins/draggable.min.js' {
  declare module.exports: $Exports<'froala-editor/js/plugins/draggable.min'>;
}
declare module 'froala-editor/js/plugins/emoticons.min.js' {
  declare module.exports: $Exports<'froala-editor/js/plugins/emoticons.min'>;
}
declare module 'froala-editor/js/plugins/entities.min.js' {
  declare module.exports: $Exports<'froala-editor/js/plugins/entities.min'>;
}
declare module 'froala-editor/js/plugins/file.min.js' {
  declare module.exports: $Exports<'froala-editor/js/plugins/file.min'>;
}
declare module 'froala-editor/js/plugins/font_family.min.js' {
  declare module.exports: $Exports<'froala-editor/js/plugins/font_family.min'>;
}
declare module 'froala-editor/js/plugins/font_size.min.js' {
  declare module.exports: $Exports<'froala-editor/js/plugins/font_size.min'>;
}
declare module 'froala-editor/js/plugins/forms.min.js' {
  declare module.exports: $Exports<'froala-editor/js/plugins/forms.min'>;
}
declare module 'froala-editor/js/plugins/fullscreen.min.js' {
  declare module.exports: $Exports<'froala-editor/js/plugins/fullscreen.min'>;
}
declare module 'froala-editor/js/plugins/help.min.js' {
  declare module.exports: $Exports<'froala-editor/js/plugins/help.min'>;
}
declare module 'froala-editor/js/plugins/image_manager.min.js' {
  declare module.exports: $Exports<'froala-editor/js/plugins/image_manager.min'>;
}
declare module 'froala-editor/js/plugins/image.min.js' {
  declare module.exports: $Exports<'froala-editor/js/plugins/image.min'>;
}
declare module 'froala-editor/js/plugins/inline_style.min.js' {
  declare module.exports: $Exports<'froala-editor/js/plugins/inline_style.min'>;
}
declare module 'froala-editor/js/plugins/line_breaker.min.js' {
  declare module.exports: $Exports<'froala-editor/js/plugins/line_breaker.min'>;
}
declare module 'froala-editor/js/plugins/link.min.js' {
  declare module.exports: $Exports<'froala-editor/js/plugins/link.min'>;
}
declare module 'froala-editor/js/plugins/lists.min.js' {
  declare module.exports: $Exports<'froala-editor/js/plugins/lists.min'>;
}
declare module 'froala-editor/js/plugins/paragraph_format.min.js' {
  declare module.exports: $Exports<'froala-editor/js/plugins/paragraph_format.min'>;
}
declare module 'froala-editor/js/plugins/paragraph_style.min.js' {
  declare module.exports: $Exports<'froala-editor/js/plugins/paragraph_style.min'>;
}
declare module 'froala-editor/js/plugins/print.min.js' {
  declare module.exports: $Exports<'froala-editor/js/plugins/print.min'>;
}
declare module 'froala-editor/js/plugins/quick_insert.min.js' {
  declare module.exports: $Exports<'froala-editor/js/plugins/quick_insert.min'>;
}
declare module 'froala-editor/js/plugins/quote.min.js' {
  declare module.exports: $Exports<'froala-editor/js/plugins/quote.min'>;
}
declare module 'froala-editor/js/plugins/save.min.js' {
  declare module.exports: $Exports<'froala-editor/js/plugins/save.min'>;
}
declare module 'froala-editor/js/plugins/special_characters.min.js' {
  declare module.exports: $Exports<'froala-editor/js/plugins/special_characters.min'>;
}
declare module 'froala-editor/js/plugins/table.min.js' {
  declare module.exports: $Exports<'froala-editor/js/plugins/table.min'>;
}
declare module 'froala-editor/js/plugins/url.min.js' {
  declare module.exports: $Exports<'froala-editor/js/plugins/url.min'>;
}
declare module 'froala-editor/js/plugins/video.min.js' {
  declare module.exports: $Exports<'froala-editor/js/plugins/video.min'>;
}
declare module 'froala-editor/js/plugins/word_paste.min.js' {
  declare module.exports: $Exports<'froala-editor/js/plugins/word_paste.min'>;
}
declare module 'froala-editor/js/third_party/image_aviary.min.js' {
  declare module.exports: $Exports<'froala-editor/js/third_party/image_aviary.min'>;
}
declare module 'froala-editor/js/third_party/spell_checker.min.js' {
  declare module.exports: $Exports<'froala-editor/js/third_party/spell_checker.min'>;
}
