// flow-typed signature: 27a54290912ed4459897e02938fb5ccb
// flow-typed version: <<STUB>>/microseconds_v^0.1.0/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'microseconds'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'microseconds' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'microseconds/now' {
  declare module.exports: any;
}

declare module 'microseconds/parse' {
  declare module.exports: any;
}

// Filename aliases
declare module 'microseconds/index' {
  declare module.exports: $Exports<'microseconds'>;
}
declare module 'microseconds/index.js' {
  declare module.exports: $Exports<'microseconds'>;
}
declare module 'microseconds/now.js' {
  declare module.exports: $Exports<'microseconds/now'>;
}
declare module 'microseconds/parse.js' {
  declare module.exports: $Exports<'microseconds/parse'>;
}
