// flow-typed signature: 0680e68ccd8749e187f1f825f3dbb9b0
// flow-typed version: <<STUB>>/react-froala-wysiwyg_v^2.6.1/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-froala-wysiwyg'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-froala-wysiwyg' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-froala-wysiwyg/bundle/FroalaEditorA' {
  declare module.exports: any;
}

declare module 'react-froala-wysiwyg/bundle/FroalaEditorA.src' {
  declare module.exports: any;
}

declare module 'react-froala-wysiwyg/bundle/FroalaEditorButton' {
  declare module.exports: any;
}

declare module 'react-froala-wysiwyg/bundle/FroalaEditorButton.src' {
  declare module.exports: any;
}

declare module 'react-froala-wysiwyg/bundle/FroalaEditorImg' {
  declare module.exports: any;
}

declare module 'react-froala-wysiwyg/bundle/FroalaEditorImg.src' {
  declare module.exports: any;
}

declare module 'react-froala-wysiwyg/bundle/FroalaEditorInput' {
  declare module.exports: any;
}

declare module 'react-froala-wysiwyg/bundle/FroalaEditorInput.src' {
  declare module.exports: any;
}

declare module 'react-froala-wysiwyg/bundle/FroalaEditorView' {
  declare module.exports: any;
}

declare module 'react-froala-wysiwyg/bundle/FroalaEditorView.src' {
  declare module.exports: any;
}

declare module 'react-froala-wysiwyg/bundle/index' {
  declare module.exports: any;
}

declare module 'react-froala-wysiwyg/bundle/index.src' {
  declare module.exports: any;
}

declare module 'react-froala-wysiwyg/configs/bs-config' {
  declare module.exports: any;
}

declare module 'react-froala-wysiwyg/demo/src/basic' {
  declare module.exports: any;
}

declare module 'react-froala-wysiwyg/demo/src/edit_inline' {
  declare module.exports: any;
}

declare module 'react-froala-wysiwyg/demo/src/full_editor' {
  declare module.exports: any;
}

declare module 'react-froala-wysiwyg/demo/src/init_on_button' {
  declare module.exports: any;
}

declare module 'react-froala-wysiwyg/demo/src/init_on_image' {
  declare module.exports: any;
}

declare module 'react-froala-wysiwyg/demo/src/init_on_input' {
  declare module.exports: any;
}

declare module 'react-froala-wysiwyg/demo/src/init_on_link' {
  declare module.exports: any;
}

declare module 'react-froala-wysiwyg/demo/src/manual_initialization' {
  declare module.exports: any;
}

declare module 'react-froala-wysiwyg/demo/src/two_way_binding' {
  declare module.exports: any;
}

declare module 'react-froala-wysiwyg/demo/webpack.config' {
  declare module.exports: any;
}

declare module 'react-froala-wysiwyg/FroalaEditorA' {
  declare module.exports: any;
}

declare module 'react-froala-wysiwyg/FroalaEditorA.src' {
  declare module.exports: any;
}

declare module 'react-froala-wysiwyg/FroalaEditorButton' {
  declare module.exports: any;
}

declare module 'react-froala-wysiwyg/FroalaEditorButton.src' {
  declare module.exports: any;
}

declare module 'react-froala-wysiwyg/FroalaEditorImg' {
  declare module.exports: any;
}

declare module 'react-froala-wysiwyg/FroalaEditorImg.src' {
  declare module.exports: any;
}

declare module 'react-froala-wysiwyg/FroalaEditorInput' {
  declare module.exports: any;
}

declare module 'react-froala-wysiwyg/FroalaEditorInput.src' {
  declare module.exports: any;
}

declare module 'react-froala-wysiwyg/FroalaEditorView' {
  declare module.exports: any;
}

declare module 'react-froala-wysiwyg/FroalaEditorView.src' {
  declare module.exports: any;
}

declare module 'react-froala-wysiwyg/index.src' {
  declare module.exports: any;
}

declare module 'react-froala-wysiwyg/lib/FroalaEditor' {
  declare module.exports: any;
}

declare module 'react-froala-wysiwyg/lib/FroalaEditorA' {
  declare module.exports: any;
}

declare module 'react-froala-wysiwyg/lib/FroalaEditorButton' {
  declare module.exports: any;
}

declare module 'react-froala-wysiwyg/lib/FroalaEditorFunctionality' {
  declare module.exports: any;
}

declare module 'react-froala-wysiwyg/lib/FroalaEditorImg' {
  declare module.exports: any;
}

declare module 'react-froala-wysiwyg/lib/FroalaEditorInput' {
  declare module.exports: any;
}

declare module 'react-froala-wysiwyg/lib/FroalaEditorView' {
  declare module.exports: any;
}

declare module 'react-froala-wysiwyg/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-froala-wysiwyg/bundle/FroalaEditorA.js' {
  declare module.exports: $Exports<"react-froala-wysiwyg/bundle/FroalaEditorA">;
}
declare module 'react-froala-wysiwyg/bundle/FroalaEditorA.src.js' {
  declare module.exports: $Exports<"react-froala-wysiwyg/bundle/FroalaEditorA.src">;
}
declare module 'react-froala-wysiwyg/bundle/FroalaEditorButton.js' {
  declare module.exports: $Exports<"react-froala-wysiwyg/bundle/FroalaEditorButton">;
}
declare module 'react-froala-wysiwyg/bundle/FroalaEditorButton.src.js' {
  declare module.exports: $Exports<"react-froala-wysiwyg/bundle/FroalaEditorButton.src">;
}
declare module 'react-froala-wysiwyg/bundle/FroalaEditorImg.js' {
  declare module.exports: $Exports<"react-froala-wysiwyg/bundle/FroalaEditorImg">;
}
declare module 'react-froala-wysiwyg/bundle/FroalaEditorImg.src.js' {
  declare module.exports: $Exports<"react-froala-wysiwyg/bundle/FroalaEditorImg.src">;
}
declare module 'react-froala-wysiwyg/bundle/FroalaEditorInput.js' {
  declare module.exports: $Exports<"react-froala-wysiwyg/bundle/FroalaEditorInput">;
}
declare module 'react-froala-wysiwyg/bundle/FroalaEditorInput.src.js' {
  declare module.exports: $Exports<"react-froala-wysiwyg/bundle/FroalaEditorInput.src">;
}
declare module 'react-froala-wysiwyg/bundle/FroalaEditorView.js' {
  declare module.exports: $Exports<"react-froala-wysiwyg/bundle/FroalaEditorView">;
}
declare module 'react-froala-wysiwyg/bundle/FroalaEditorView.src.js' {
  declare module.exports: $Exports<"react-froala-wysiwyg/bundle/FroalaEditorView.src">;
}
declare module 'react-froala-wysiwyg/bundle/index.js' {
  declare module.exports: $Exports<"react-froala-wysiwyg/bundle/index">;
}
declare module 'react-froala-wysiwyg/bundle/index.src.js' {
  declare module.exports: $Exports<"react-froala-wysiwyg/bundle/index.src">;
}
declare module 'react-froala-wysiwyg/configs/bs-config.js' {
  declare module.exports: $Exports<"react-froala-wysiwyg/configs/bs-config">;
}
declare module 'react-froala-wysiwyg/demo/src/basic.jsx' {
  declare module.exports: $Exports<"react-froala-wysiwyg/demo/src/basic">;
}
declare module 'react-froala-wysiwyg/demo/src/edit_inline.jsx' {
  declare module.exports: $Exports<"react-froala-wysiwyg/demo/src/edit_inline">;
}
declare module 'react-froala-wysiwyg/demo/src/full_editor.jsx' {
  declare module.exports: $Exports<"react-froala-wysiwyg/demo/src/full_editor">;
}
declare module 'react-froala-wysiwyg/demo/src/init_on_button.jsx' {
  declare module.exports: $Exports<"react-froala-wysiwyg/demo/src/init_on_button">;
}
declare module 'react-froala-wysiwyg/demo/src/init_on_image.jsx' {
  declare module.exports: $Exports<"react-froala-wysiwyg/demo/src/init_on_image">;
}
declare module 'react-froala-wysiwyg/demo/src/init_on_input.jsx' {
  declare module.exports: $Exports<"react-froala-wysiwyg/demo/src/init_on_input">;
}
declare module 'react-froala-wysiwyg/demo/src/init_on_link.jsx' {
  declare module.exports: $Exports<"react-froala-wysiwyg/demo/src/init_on_link">;
}
declare module 'react-froala-wysiwyg/demo/src/manual_initialization.jsx' {
  declare module.exports: $Exports<"react-froala-wysiwyg/demo/src/manual_initialization">;
}
declare module 'react-froala-wysiwyg/demo/src/two_way_binding.jsx' {
  declare module.exports: $Exports<"react-froala-wysiwyg/demo/src/two_way_binding">;
}
declare module 'react-froala-wysiwyg/demo/webpack.config.js' {
  declare module.exports: $Exports<"react-froala-wysiwyg/demo/webpack.config">;
}
declare module 'react-froala-wysiwyg/FroalaEditorA.js' {
  declare module.exports: $Exports<"react-froala-wysiwyg/FroalaEditorA">;
}
declare module 'react-froala-wysiwyg/FroalaEditorA.src.js' {
  declare module.exports: $Exports<"react-froala-wysiwyg/FroalaEditorA.src">;
}
declare module 'react-froala-wysiwyg/FroalaEditorButton.js' {
  declare module.exports: $Exports<"react-froala-wysiwyg/FroalaEditorButton">;
}
declare module 'react-froala-wysiwyg/FroalaEditorButton.src.js' {
  declare module.exports: $Exports<"react-froala-wysiwyg/FroalaEditorButton.src">;
}
declare module 'react-froala-wysiwyg/FroalaEditorImg.js' {
  declare module.exports: $Exports<"react-froala-wysiwyg/FroalaEditorImg">;
}
declare module 'react-froala-wysiwyg/FroalaEditorImg.src.js' {
  declare module.exports: $Exports<"react-froala-wysiwyg/FroalaEditorImg.src">;
}
declare module 'react-froala-wysiwyg/FroalaEditorInput.js' {
  declare module.exports: $Exports<"react-froala-wysiwyg/FroalaEditorInput">;
}
declare module 'react-froala-wysiwyg/FroalaEditorInput.src.js' {
  declare module.exports: $Exports<"react-froala-wysiwyg/FroalaEditorInput.src">;
}
declare module 'react-froala-wysiwyg/FroalaEditorView.js' {
  declare module.exports: $Exports<"react-froala-wysiwyg/FroalaEditorView">;
}
declare module 'react-froala-wysiwyg/FroalaEditorView.src.js' {
  declare module.exports: $Exports<"react-froala-wysiwyg/FroalaEditorView.src">;
}
declare module 'react-froala-wysiwyg/index' {
  declare module.exports: $Exports<"react-froala-wysiwyg">;
}
declare module 'react-froala-wysiwyg/index.js' {
  declare module.exports: $Exports<"react-froala-wysiwyg">;
}
declare module 'react-froala-wysiwyg/index.src.js' {
  declare module.exports: $Exports<"react-froala-wysiwyg/index.src">;
}
declare module 'react-froala-wysiwyg/lib/FroalaEditor.jsx' {
  declare module.exports: $Exports<"react-froala-wysiwyg/lib/FroalaEditor">;
}
declare module 'react-froala-wysiwyg/lib/FroalaEditorA.jsx' {
  declare module.exports: $Exports<"react-froala-wysiwyg/lib/FroalaEditorA">;
}
declare module 'react-froala-wysiwyg/lib/FroalaEditorButton.jsx' {
  declare module.exports: $Exports<"react-froala-wysiwyg/lib/FroalaEditorButton">;
}
declare module 'react-froala-wysiwyg/lib/FroalaEditorFunctionality.jsx' {
  declare module.exports: $Exports<"react-froala-wysiwyg/lib/FroalaEditorFunctionality">;
}
declare module 'react-froala-wysiwyg/lib/FroalaEditorImg.jsx' {
  declare module.exports: $Exports<"react-froala-wysiwyg/lib/FroalaEditorImg">;
}
declare module 'react-froala-wysiwyg/lib/FroalaEditorInput.jsx' {
  declare module.exports: $Exports<"react-froala-wysiwyg/lib/FroalaEditorInput">;
}
declare module 'react-froala-wysiwyg/lib/FroalaEditorView.jsx' {
  declare module.exports: $Exports<"react-froala-wysiwyg/lib/FroalaEditorView">;
}
declare module 'react-froala-wysiwyg/webpack.config.js' {
  declare module.exports: $Exports<"react-froala-wysiwyg/webpack.config">;
}
