// flow-typed signature: 8fe93498fce93f97dc70437d8714c01a
// flow-typed version: <<STUB>>/webpack-config_v^7.0.0/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'webpack-config'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'webpack-config' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'webpack-config/dist/Config' {
  declare module.exports: any;
}

declare module 'webpack-config/dist/ConfigArgv' {
  declare module.exports: any;
}

declare module 'webpack-config/dist/ConfigCache' {
  declare module.exports: any;
}

declare module 'webpack-config/dist/ConfigCacheResolvers' {
  declare module.exports: any;
}

declare module 'webpack-config/dist/ConfigCleanupTransform' {
  declare module.exports: any;
}

declare module 'webpack-config/dist/ConfigCommand' {
  declare module.exports: any;
}

declare module 'webpack-config/dist/ConfigCommandFactory' {
  declare module.exports: any;
}

declare module 'webpack-config/dist/ConfigCommandInvoker' {
  declare module.exports: any;
}

declare module 'webpack-config/dist/ConfigCommandNames' {
  declare module.exports: any;
}

declare module 'webpack-config/dist/ConfigCommandTypes' {
  declare module.exports: any;
}

declare module 'webpack-config/dist/ConfigContainer' {
  declare module.exports: any;
}

declare module 'webpack-config/dist/ConfigDefaultsCommand' {
  declare module.exports: any;
}

declare module 'webpack-config/dist/ConfigDefaultTransform' {
  declare module.exports: any;
}

declare module 'webpack-config/dist/ConfigDependency' {
  declare module.exports: any;
}

declare module 'webpack-config/dist/ConfigDependencyIterator' {
  declare module.exports: any;
}

declare module 'webpack-config/dist/ConfigEnvironment' {
  declare module.exports: any;
}

declare module 'webpack-config/dist/ConfigExtendCommand' {
  declare module.exports: any;
}

declare module 'webpack-config/dist/ConfigFactory' {
  declare module.exports: any;
}

declare module 'webpack-config/dist/ConfigList' {
  declare module.exports: any;
}

declare module 'webpack-config/dist/ConfigLoader' {
  declare module.exports: any;
}

declare module 'webpack-config/dist/ConfigMergeCommand' {
  declare module.exports: any;
}

declare module 'webpack-config/dist/ConfigOptionsResolver' {
  declare module.exports: any;
}

declare module 'webpack-config/dist/ConfigPathResolver' {
  declare module.exports: any;
}

declare module 'webpack-config/dist/ConfigPathResolvers' {
  declare module.exports: any;
}

declare module 'webpack-config/dist/ConfigPatternCache' {
  declare module.exports: any;
}

declare module 'webpack-config/dist/ConfigStrategyList' {
  declare module.exports: any;
}

declare module 'webpack-config/dist/ConfigStringResolver' {
  declare module.exports: any;
}

declare module 'webpack-config/dist/index' {
  declare module.exports: any;
}

declare module 'webpack-config/src/Config' {
  declare module.exports: any;
}

declare module 'webpack-config/src/ConfigArgv' {
  declare module.exports: any;
}

declare module 'webpack-config/src/ConfigCache' {
  declare module.exports: any;
}

declare module 'webpack-config/src/ConfigCacheResolvers' {
  declare module.exports: any;
}

declare module 'webpack-config/src/ConfigCleanupTransform' {
  declare module.exports: any;
}

declare module 'webpack-config/src/ConfigCommand' {
  declare module.exports: any;
}

declare module 'webpack-config/src/ConfigCommandFactory' {
  declare module.exports: any;
}

declare module 'webpack-config/src/ConfigCommandInvoker' {
  declare module.exports: any;
}

declare module 'webpack-config/src/ConfigCommandNames' {
  declare module.exports: any;
}

declare module 'webpack-config/src/ConfigCommandTypes' {
  declare module.exports: any;
}

declare module 'webpack-config/src/ConfigContainer' {
  declare module.exports: any;
}

declare module 'webpack-config/src/ConfigDefaultsCommand' {
  declare module.exports: any;
}

declare module 'webpack-config/src/ConfigDefaultTransform' {
  declare module.exports: any;
}

declare module 'webpack-config/src/ConfigDependency' {
  declare module.exports: any;
}

declare module 'webpack-config/src/ConfigDependencyIterator' {
  declare module.exports: any;
}

declare module 'webpack-config/src/ConfigEnvironment' {
  declare module.exports: any;
}

declare module 'webpack-config/src/ConfigExtendCommand' {
  declare module.exports: any;
}

declare module 'webpack-config/src/ConfigFactory' {
  declare module.exports: any;
}

declare module 'webpack-config/src/ConfigList' {
  declare module.exports: any;
}

declare module 'webpack-config/src/ConfigLoader' {
  declare module.exports: any;
}

declare module 'webpack-config/src/ConfigMergeCommand' {
  declare module.exports: any;
}

declare module 'webpack-config/src/ConfigOptionsResolver' {
  declare module.exports: any;
}

declare module 'webpack-config/src/ConfigPathResolver' {
  declare module.exports: any;
}

declare module 'webpack-config/src/ConfigPathResolvers' {
  declare module.exports: any;
}

declare module 'webpack-config/src/ConfigPatternCache' {
  declare module.exports: any;
}

declare module 'webpack-config/src/ConfigStrategyList' {
  declare module.exports: any;
}

declare module 'webpack-config/src/ConfigStringResolver' {
  declare module.exports: any;
}

declare module 'webpack-config/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'webpack-config/dist/Config.js' {
  declare module.exports: $Exports<'webpack-config/dist/Config'>;
}
declare module 'webpack-config/dist/ConfigArgv.js' {
  declare module.exports: $Exports<'webpack-config/dist/ConfigArgv'>;
}
declare module 'webpack-config/dist/ConfigCache.js' {
  declare module.exports: $Exports<'webpack-config/dist/ConfigCache'>;
}
declare module 'webpack-config/dist/ConfigCacheResolvers.js' {
  declare module.exports: $Exports<'webpack-config/dist/ConfigCacheResolvers'>;
}
declare module 'webpack-config/dist/ConfigCleanupTransform.js' {
  declare module.exports: $Exports<'webpack-config/dist/ConfigCleanupTransform'>;
}
declare module 'webpack-config/dist/ConfigCommand.js' {
  declare module.exports: $Exports<'webpack-config/dist/ConfigCommand'>;
}
declare module 'webpack-config/dist/ConfigCommandFactory.js' {
  declare module.exports: $Exports<'webpack-config/dist/ConfigCommandFactory'>;
}
declare module 'webpack-config/dist/ConfigCommandInvoker.js' {
  declare module.exports: $Exports<'webpack-config/dist/ConfigCommandInvoker'>;
}
declare module 'webpack-config/dist/ConfigCommandNames.js' {
  declare module.exports: $Exports<'webpack-config/dist/ConfigCommandNames'>;
}
declare module 'webpack-config/dist/ConfigCommandTypes.js' {
  declare module.exports: $Exports<'webpack-config/dist/ConfigCommandTypes'>;
}
declare module 'webpack-config/dist/ConfigContainer.js' {
  declare module.exports: $Exports<'webpack-config/dist/ConfigContainer'>;
}
declare module 'webpack-config/dist/ConfigDefaultsCommand.js' {
  declare module.exports: $Exports<'webpack-config/dist/ConfigDefaultsCommand'>;
}
declare module 'webpack-config/dist/ConfigDefaultTransform.js' {
  declare module.exports: $Exports<'webpack-config/dist/ConfigDefaultTransform'>;
}
declare module 'webpack-config/dist/ConfigDependency.js' {
  declare module.exports: $Exports<'webpack-config/dist/ConfigDependency'>;
}
declare module 'webpack-config/dist/ConfigDependencyIterator.js' {
  declare module.exports: $Exports<'webpack-config/dist/ConfigDependencyIterator'>;
}
declare module 'webpack-config/dist/ConfigEnvironment.js' {
  declare module.exports: $Exports<'webpack-config/dist/ConfigEnvironment'>;
}
declare module 'webpack-config/dist/ConfigExtendCommand.js' {
  declare module.exports: $Exports<'webpack-config/dist/ConfigExtendCommand'>;
}
declare module 'webpack-config/dist/ConfigFactory.js' {
  declare module.exports: $Exports<'webpack-config/dist/ConfigFactory'>;
}
declare module 'webpack-config/dist/ConfigList.js' {
  declare module.exports: $Exports<'webpack-config/dist/ConfigList'>;
}
declare module 'webpack-config/dist/ConfigLoader.js' {
  declare module.exports: $Exports<'webpack-config/dist/ConfigLoader'>;
}
declare module 'webpack-config/dist/ConfigMergeCommand.js' {
  declare module.exports: $Exports<'webpack-config/dist/ConfigMergeCommand'>;
}
declare module 'webpack-config/dist/ConfigOptionsResolver.js' {
  declare module.exports: $Exports<'webpack-config/dist/ConfigOptionsResolver'>;
}
declare module 'webpack-config/dist/ConfigPathResolver.js' {
  declare module.exports: $Exports<'webpack-config/dist/ConfigPathResolver'>;
}
declare module 'webpack-config/dist/ConfigPathResolvers.js' {
  declare module.exports: $Exports<'webpack-config/dist/ConfigPathResolvers'>;
}
declare module 'webpack-config/dist/ConfigPatternCache.js' {
  declare module.exports: $Exports<'webpack-config/dist/ConfigPatternCache'>;
}
declare module 'webpack-config/dist/ConfigStrategyList.js' {
  declare module.exports: $Exports<'webpack-config/dist/ConfigStrategyList'>;
}
declare module 'webpack-config/dist/ConfigStringResolver.js' {
  declare module.exports: $Exports<'webpack-config/dist/ConfigStringResolver'>;
}
declare module 'webpack-config/dist/index.js' {
  declare module.exports: $Exports<'webpack-config/dist/index'>;
}
declare module 'webpack-config/src/Config.js' {
  declare module.exports: $Exports<'webpack-config/src/Config'>;
}
declare module 'webpack-config/src/ConfigArgv.js' {
  declare module.exports: $Exports<'webpack-config/src/ConfigArgv'>;
}
declare module 'webpack-config/src/ConfigCache.js' {
  declare module.exports: $Exports<'webpack-config/src/ConfigCache'>;
}
declare module 'webpack-config/src/ConfigCacheResolvers.js' {
  declare module.exports: $Exports<'webpack-config/src/ConfigCacheResolvers'>;
}
declare module 'webpack-config/src/ConfigCleanupTransform.js' {
  declare module.exports: $Exports<'webpack-config/src/ConfigCleanupTransform'>;
}
declare module 'webpack-config/src/ConfigCommand.js' {
  declare module.exports: $Exports<'webpack-config/src/ConfigCommand'>;
}
declare module 'webpack-config/src/ConfigCommandFactory.js' {
  declare module.exports: $Exports<'webpack-config/src/ConfigCommandFactory'>;
}
declare module 'webpack-config/src/ConfigCommandInvoker.js' {
  declare module.exports: $Exports<'webpack-config/src/ConfigCommandInvoker'>;
}
declare module 'webpack-config/src/ConfigCommandNames.js' {
  declare module.exports: $Exports<'webpack-config/src/ConfigCommandNames'>;
}
declare module 'webpack-config/src/ConfigCommandTypes.js' {
  declare module.exports: $Exports<'webpack-config/src/ConfigCommandTypes'>;
}
declare module 'webpack-config/src/ConfigContainer.js' {
  declare module.exports: $Exports<'webpack-config/src/ConfigContainer'>;
}
declare module 'webpack-config/src/ConfigDefaultsCommand.js' {
  declare module.exports: $Exports<'webpack-config/src/ConfigDefaultsCommand'>;
}
declare module 'webpack-config/src/ConfigDefaultTransform.js' {
  declare module.exports: $Exports<'webpack-config/src/ConfigDefaultTransform'>;
}
declare module 'webpack-config/src/ConfigDependency.js' {
  declare module.exports: $Exports<'webpack-config/src/ConfigDependency'>;
}
declare module 'webpack-config/src/ConfigDependencyIterator.js' {
  declare module.exports: $Exports<'webpack-config/src/ConfigDependencyIterator'>;
}
declare module 'webpack-config/src/ConfigEnvironment.js' {
  declare module.exports: $Exports<'webpack-config/src/ConfigEnvironment'>;
}
declare module 'webpack-config/src/ConfigExtendCommand.js' {
  declare module.exports: $Exports<'webpack-config/src/ConfigExtendCommand'>;
}
declare module 'webpack-config/src/ConfigFactory.js' {
  declare module.exports: $Exports<'webpack-config/src/ConfigFactory'>;
}
declare module 'webpack-config/src/ConfigList.js' {
  declare module.exports: $Exports<'webpack-config/src/ConfigList'>;
}
declare module 'webpack-config/src/ConfigLoader.js' {
  declare module.exports: $Exports<'webpack-config/src/ConfigLoader'>;
}
declare module 'webpack-config/src/ConfigMergeCommand.js' {
  declare module.exports: $Exports<'webpack-config/src/ConfigMergeCommand'>;
}
declare module 'webpack-config/src/ConfigOptionsResolver.js' {
  declare module.exports: $Exports<'webpack-config/src/ConfigOptionsResolver'>;
}
declare module 'webpack-config/src/ConfigPathResolver.js' {
  declare module.exports: $Exports<'webpack-config/src/ConfigPathResolver'>;
}
declare module 'webpack-config/src/ConfigPathResolvers.js' {
  declare module.exports: $Exports<'webpack-config/src/ConfigPathResolvers'>;
}
declare module 'webpack-config/src/ConfigPatternCache.js' {
  declare module.exports: $Exports<'webpack-config/src/ConfigPatternCache'>;
}
declare module 'webpack-config/src/ConfigStrategyList.js' {
  declare module.exports: $Exports<'webpack-config/src/ConfigStrategyList'>;
}
declare module 'webpack-config/src/ConfigStringResolver.js' {
  declare module.exports: $Exports<'webpack-config/src/ConfigStringResolver'>;
}
declare module 'webpack-config/src/index.js' {
  declare module.exports: $Exports<'webpack-config/src/index'>;
}
