version: 2
jobs:
  build:
    working_directory: ~/rian
    docker:
        - image: ceruberu/rian-primary:0.1.0
    environment:
            AWS_CODE_DEPLOY_REGION: ap-northeast-2
            AWS_CODE_DEPLOY_APPLICATION_NAME: "rian-application"
            AWS_CODE_DEPLOY_DEPLOYMENT_CONFIG_NAME: CodeDeployDefault.AllAtOnce
            AWS_CODE_DEPLOY_DEPLOYMENT_GROUP_NAME: "rian-deploy-group"
            AWS_CODE_DEPLOY_SERVICE_ROLE_ARN: "arn:aws:iam::161388893601:role/rian-role-admin"
            AWS_CODE_DEPLOY_EC2_TAG_FILTERS: "Key=rian,Value=projects,Type=KEY_AND_VALUE"
            AWS_CODE_DEPLOY_S3_FILENAME: "${CIRCLE_BUILD_NUM}#${CIRCLE_SHA1:0:7}.zip"
            AWS_CODE_DEPLOY_S3_BUCKET: rian-s3-dev
            AWS_CODE_DEPLOY_S3_KEY_PREFIX: "production-rian"
            AWS_CODE_DEPLOY_S3_LIMIT_BUCKET_FILES: 3
            AWS_CODE_DEPLOY_S3_SSE: true
            AWS_CODE_DEPLOY_REVISION_DESCRIPTION: "${CIRCLE_BRANCH} (#${CIRCLE_SHA1:0:7})"
            AWS_CODE_DEPLOY_DEPLOYMENT_DESCRIPTION: "Deployed via CircleCI on $(date)"
    steps:
        - checkout
        - run:
            name: Pre-Dependencies
            command: mkdir ~/rian/artifacts
        - restore_cache:
            keys: 
              - rian-{{ .Branch }}-{{ checksum "yarn.lock" }}
              - rian-{{ .Branch }}-
              - rian-master
            paths:
              - ~/.cache/yarn
        - run:
            name: Install Dependencies
            command: yarn install
        - run:
            name: Build
            command: yarn build
        # - run:
        #     name: Test
        #     command: |
        #       node -v
        #       yarn run test:ci
        - save_cache:
            key: rian-{{ .Branch }}-{{ checksum "yarn.lock" }}
            paths:
              - ~/.cache/yarn
        - deploy:
            command: bash ~/rian/scripts/circleci/aws-code-deploy.sh
        - store_artifacts:
            path: ~/rian/artifacts
            destination: prefix
        - store_test_results:
            path: ~/rian/test-results
